from __future__ import annotations

from .base import AppTheme, ThemePalette


LIGHT_THEME = AppTheme(
    id="light",
    display_name="Light",
    palette=ThemePalette(
        bg0="#f6f8fa",
        bg1="#ffffff",
        bg2="#f0f3f6",
        bg3="#dce3ec",
        surface="#ffffff",
        surface_card="#ffffff",
        surface_alt="#f3f6fa",
        surface_input_focus="#ffffff",
        surface_hover="#f1f5f9",
        surface_hover_strong="#e8eef6",
        surface_overlay="#ffffff",
        media_placeholder="#e5eaf1",
        border="#d0d7de",
        border_muted="#d8dee4",
        border_subtle="#eaeef2",
        border_strong="#afb8c1",
        text_primary="#24292f",
        text_secondary="#57606a",
        text_muted="#6e7781",
        text_dim="#8c959f",
        text_faint="#57606a",
        text_on_accent="#ffffff",
        accent="#0969da",
        accent_alt="#0969da",
        accent_hover="#0550ae",
        accent_pressed="#033d8b",
        accent_selection="#0969da",
        accent_muted="#ddf4ff",
        accent_muted_hover="#b6e3ff",
        accent_tint="#f0f7ff",
        accent_text="#0969da",
        accent_text_hover="#0550ae",
        success="#1a7f37",
        success_surface="#dafbe1",
        success_surface_strong="#aceebb",
        success_border="#4ac26b",
        success_hover="#2da44e",
        success_pressed="#116329",
        warning="#9a6700",
        warning_text="#9a6700",
        danger="#cf222e",
        danger_text="#cf222e",
        danger_surface="#ffebe9",
        danger_border="#ff8182",
        danger_surface_hover="#ffd8d3",
        danger_subtle="#ffebe9",
        projection="#1a7f37",
        titlebar="#f6f8fa",
        black="#000000",
        white="#ffffff",
    ),
    hover_opacity=0.92,
    hover_strong_opacity=0.96,
    section_hover_opacity=0.86,
)
