from __future__ import annotations

from .base import AppTheme, ThemePalette


LIGHT_THEME = AppTheme(
    id="light",
    display_name="Light",
    palette=ThemePalette(
        bg0="#e8edf3",
        bg1="#f1f5f9",
        bg2="#dde6ef",
        bg3="#bdcbd9",
        surface="#f5f8fb",
        surface_card="#f8fafc",
        surface_alt="#e6edf5",
        surface_input_focus="#ffffff",
        surface_hover="#dbe5ef",
        surface_hover_strong="#cbd9e7",
        surface_overlay="#f9fbfd",
        media_placeholder="#d8e2ec",
        border="#b8c7d6",
        border_muted="#ccd8e3",
        border_subtle="#dde6ee",
        border_strong="#96a9bc",
        text_primary="#111827",
        text_secondary="#334155",
        text_muted="#475569",
        text_dim="#64748b",
        text_faint="#536273",
        text_on_accent="#ffffff",
        accent="#1d5fd3",
        accent_alt="#256fd9",
        accent_hover="#174fb4",
        accent_pressed="#123f8f",
        accent_selection="#1d5fd3",
        accent_muted="#d9e8ff",
        accent_muted_hover="#bfd8ff",
        accent_tint="#edf5ff",
        accent_text="#164fb3",
        accent_text_hover="#123f8f",
        success="#16723a",
        success_surface="#dcf0e3",
        success_surface_strong="#bce1c9",
        success_border="#5ab878",
        success_hover="#128042",
        success_pressed="#0d5f31",
        warning="#8a5a00",
        warning_text="#7a4c00",
        warning_surface="#eef0e7",
        warning_surface_hover="#e8ecdf",
        warning_border="#cbb77f",
        danger="#b4232f",
        danger_text="#9f1d29",
        danger_surface="#f6dddf",
        danger_border="#e28a92",
        danger_surface_hover="#efc8cd",
        danger_subtle="#f6dddf",
        projection="#16723a",
        titlebar="#dfe7ef",
        black="#000000",
        white="#ffffff",
    ),
    section_header_hover_alpha=0.05,
)
