@echo off
REM Build the solin-framesrc libobs plugin on Windows (MSVC x64).
REM
REM solin-framesrc is a tiny async video source that displays frames pushed from
REM Python via obs_source_output_video() -- see solin-framesrc.c. Without it,
REM create_frame_source() returns None and Solin falls back to a Qt per-frame
REM path for the live-browser/NDI projection.
REM
REM OBS_DECLARE_MODULE() compiles the module's API version into the DLL and
REM libobs REFUSES to load a module whose obs_module_ver != obs_get_version.
REM So this MUST build against the obs-studio tag matching the bundled libobs
REM (asserted below, not assumed).
REM
REM Usage:  tools\obs-frame-source\build.bat          build + install into the venv pylibobs
REM         tools\obs-frame-source\build.bat check    verify an already-installed plugin
setlocal EnableDelayedExpansion

set "HERE=%~dp0"
set "HERE=%HERE:~0,-1%"
set "ROOT=%HERE%\..\.."
set "WORK=%TEMP%\solin-framesrc-build"
set "GEN=%WORK%\gen"
set "OUT=%WORK%\out"
set "OBSSRC=%WORK%\obs-studio"

REM The bundled libobs decides the tag. Do not bump this by hand -- read it off
REM the DLL (see the assertion further down) and change it to match.
set "OBS_TAG=32.1.2"

if "%PY%"=="" set "PY=%ROOT%\.venv\Scripts\python.exe"
if not exist "%PY%" (
  echo [ERRO] Python nao encontrado em "%PY%". Defina PY=caminho\para\python.exe
  exit /b 1
)

REM Resolve the pylibobs lib dir via a temp file: nesting quotes inside a
REM for /f back-quoted command does not survive cmd's parser.
"%PY%" -c "import os,inspect,pylibobs;print(os.path.join(os.path.dirname(inspect.getfile(pylibobs)),'_libs','windows','x86_64'))" > "%TEMP%\solin_framesrc_libdir.txt" 2>nul
set "LIBDIR="
if exist "%TEMP%\solin_framesrc_libdir.txt" set /p LIBDIR=<"%TEMP%\solin_framesrc_libdir.txt"
if "%LIBDIR%"=="" (
  echo [ERRO] Nao foi possivel localizar o pylibobs. Ele esta instalado no venv?
  exit /b 1
)
if not exist "%LIBDIR%\obs.dll" (
  echo [ERRO] obs.dll nao encontrado em "%LIBDIR%". pylibobs esta instalado?
  exit /b 1
)
set "PLUGINDIR=%LIBDIR%\obs-plugins"

echo ^>^> obs tag       : %OBS_TAG%
echo ^>^> pylibobs libs : %LIBDIR%

if /i "%~1"=="check" goto :verify

REM ---------------------------------------------------------------- toolchain
set "VCVARS=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
if not exist "%VCVARS%" set "VCVARS=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
if not exist "%VCVARS%" set "VCVARS=C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
if not exist "%VCVARS%" (
  echo [ERRO] vcvars64.bat nao encontrado. Instale o Visual Studio Build Tools 2022 ^(C++^).
  exit /b 1
)
call "%VCVARS%" >nul
if errorlevel 1 ( echo [ERRO] Falha ao carregar o ambiente MSVC. & exit /b 1 )

mkdir "%GEN%" 2>nul
mkdir "%OUT%" 2>nul

REM ------------------------------------------------------------- obs headers
REM Blobless + sparse: only libobs/ headers are needed, so this stays small.
if not exist "%OBSSRC%\libobs\obs-module.h" (
  echo ^>^> baixando headers do obs-studio %OBS_TAG% ...
  rmdir /s /q "%OBSSRC%" 2>nul
  git clone --depth 1 --branch %OBS_TAG% --filter=blob:none --sparse https://github.com/obsproject/obs-studio.git "%OBSSRC%" >nul 2>&1
  if errorlevel 1 ( echo [ERRO] git clone falhou. & exit /b 1 )
  pushd "%OBSSRC%" && git sparse-checkout set libobs >nul 2>&1 && popd
)
if not exist "%OBSSRC%\libobs\obs-module.h" (
  echo [ERRO] headers do libobs nao encontrados em "%OBSSRC%\libobs".
  exit /b 1
)

REM obsconfig.h is normally generated by CMake; libobs/obs-config.h includes it
REM unconditionally. Only the version macros are consumed by a module build --
REM the OBS_DATA_PATH/ENABLE_* macros are used solely by the nix-only .c files.
> "%GEN%\obsconfig.h" echo #pragma once
>>"%GEN%\obsconfig.h" echo #define OBS_RELEASE_CANDIDATE 0
>>"%GEN%\obsconfig.h" echo #define OBS_BETA 0

REM ------------------------------------------------------- import library
REM pylibobs ships obs.dll but no obs.lib, so synthesise one from the export
REM table. The module imports only a handful of symbols; a full .def keeps this
REM robust if the source grows.
if not exist "%OUT%\obs.lib" (
  echo ^>^> gerando obs.lib a partir de obs.dll ...
  dumpbin /nologo /exports "%LIBDIR%\obs.dll" > "%OUT%\obs-exports.txt"
  if errorlevel 1 ( echo [ERRO] dumpbin falhou. & exit /b 1 )
  "%PY%" -c "import re,sys;src,dst=sys.argv[1],sys.argv[2];names=[m.group(1) for m in (re.match(r'^\s*\d+\s+[0-9A-Fa-f]+\s+[0-9A-Fa-f]+\s+(\S+)',l) for l in open(src,encoding='utf-8',errors='replace')) if m];open(dst,'w').write('LIBRARY obs\nEXPORTS\n'+''.join('    '+n+'\n' for n in names));print(len(names),'simbolos')" "%OUT%\obs-exports.txt" "%OUT%\obs.def"
  if errorlevel 1 ( echo [ERRO] falha ao gerar obs.def. & exit /b 1 )
  lib /nologo /def:"%OUT%\obs.def" /machine:x64 /out:"%OUT%\obs.lib" >nul
  if errorlevel 1 ( echo [ERRO] lib.exe falhou. & exit /b 1 )
)

REM -------------------------------------------------------------- compile
REM /TC forces C: the obs_source_info initialiser uses C99 designated
REM initialisers, which MSVC rejects in C++ mode below /std:c++20.
REM /MT (static CRT) matches tools\solin-dshowcam and keeps the plugin free of
REM any vcruntime resolution question inside obs-plugins\, which the packaging
REM script's MSVC-runtime copy does not cover.
echo ^>^> compilando solin-framesrc.dll ...
cl /nologo /LD /TC /std:c17 /O2 /W3 /MT /D_CRT_SECURE_NO_WARNINGS ^
   /I "%GEN%" /I "%OBSSRC%\libobs" ^
   "%HERE%\solin-framesrc.c" /Fo"%OUT%\\" /Fe"%OUT%\solin-framesrc.dll" ^
   /link /LIBPATH:"%OUT%" obs.lib
if errorlevel 1 ( echo [ERRO] compilacao falhou. & exit /b 1 )

REM ---------------------------------------------------------------- install
if not exist "%PLUGINDIR%" mkdir "%PLUGINDIR%"
copy /y "%OUT%\solin-framesrc.dll" "%PLUGINDIR%\solin-framesrc.dll" >nul
if errorlevel 1 ( echo [ERRO] falha ao instalar o plugin. & exit /b 1 )
echo ^>^> instalado -^> %PLUGINDIR%\solin-framesrc.dll

:verify
REM Assert the compiled-in module API version matches the bundled libobs. A
REM mismatch here is exactly what makes libobs silently refuse to load the
REM module, so fail loudly rather than shipping a plugin that never loads.
"%PY%" -c "import ctypes,os,sys;d=sys.argv[1];p=os.path.join(d,'obs-plugins','solin-framesrc.dll');os.add_dll_directory(d);m=ctypes.CDLL(p);m.obs_module_ver.restype=ctypes.c_uint32;o=ctypes.CDLL(os.path.join(d,'obs.dll'));o.obs_get_version.restype=ctypes.c_uint32;a,b=m.obs_module_ver(),o.obs_get_version();print('   module API =',a,'| libobs =',b);sys.exit(0 if a==b else 2)" "%LIBDIR%"
if errorlevel 1 (
  echo [ERRO] versao da API do modulo nao confere com o libobs empacotado.
  exit /b 1
)
echo ^>^> OK: a API do modulo confere com o libobs empacotado.
echo ^>^> pronto.
endlocal
